Refactor skills
johnnypowa/knightvszombie pull request #4
Opened 2022-06-30 22:29 UTC by johnnypowa

### Refactor skills

-AppDatabase version change 1 to 2
-Create typeConverter to skillList
-Add skills columnInfo to KnightEntity
-Add skillList to Knight
-Create skills in CombatLocalDataSource
-Add skills to skillList in CombatLocalDataSource
-Add skillList to KnightDao.insertKnight in CombatLocalDataSource
-Create skillActivation function and checkEquippedSkills function, remove old skill functions on CombatFragment
-Use skillActivation function on knightSkills setOnClickListeners
-Add skillList to knightEntityData on CombatViewModel
-Create Skill class

### Plan

-Show the equipped skills icons and names on the CombatFragment
-Create RecyclerView layout for skills 
-Users can equip or unequip the skills on the skills fragment. Max. 4 skills can be equipped.

2022-07-11 07:02 UTC, csepidave requested changes
There are some small formatting issues and issues which we have to discuss.
But overall nice work! 👍

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +    fun checkEquippedSkills(){
let's talk about it :speech_balloon:

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +    fun skillActivation(index : Int){
let's talk about it :speech_balloon:

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/service/datasource/CombatLocalDataSource.kt
> +                var skillList = arrayListOf(skillExtraDamage,skillCriticalHit,skillPrecisionHit,skillLifeSteal,skillHeal)
segmentation!
```
arrayListOf(skillExtraDamage, skillCriticalHit, skillPrecisionHit, skillLifeSteal, skillHeal)
```

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/service/datasource/CombatLocalDataSource.kt
> +    var skillExtraDamage = Skill("Dupla ütés", 1,0,100,0f,0f,0f,true)
Please pay attention to segmentation!
```
Skill("Dupla ütés", 1, 0, 100, 0f, 0f , 0f, true)
```

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/model/Skill.kt
> +                 var criticalHitChance: Float,
Use the same segmentation like this on the other lines too.

2022-07-11 07:02 UTC, csepidave commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +            getString(R.string.skill_double_hit)->{
segmentation

2022-07-12 19:21 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/service/datasource/CombatLocalDataSource.kt
> +    var skillExtraDamage = Skill("Dupla ütés", 1,0,100,0f,0f,0f,true)
Done

2022-07-12 19:21 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/service/datasource/CombatLocalDataSource.kt
> +                var skillList = arrayListOf(skillExtraDamage,skillCriticalHit,skillPrecisionHit,skillLifeSteal,skillHeal)
Done

2022-07-12 19:23 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/model/Skill.kt
> +                 var criticalHitChance: Float,
Done

2022-07-12 19:30 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +            getString(R.string.skill_double_hit)->{
Done

2022-07-12 20:09 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +    fun checkEquippedSkills(){
Done

2022-07-12 20:30 UTC, johnnypowa commented on app/src/main/java/com/example/tanuls2/ui/view/CombatFragment.kt
> +    fun skillActivation(index : Int){
Done

2022-07-12 20:50 UTC, csepidave approved these changes

2022-07-12 20:50 UTC, merged